[package]
description = "Parity Dapps crate"
name = "ethcore-dapps"
version = "1.4.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]
build = "build.rs"

[lib]

[dependencies]
rand = "0.3.14"
log = "0.3"
jsonrpc-core = "3.0"
jsonrpc-http-server = { git = "https://github.com/ethcore/jsonrpc-http-server.git" }
hyper = { default-features = false, git = "https://github.com/ethcore/hyper" }
unicase = "1.3"
url = "1.0"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
serde_macros = { version = "0.8", optional = true }
zip = { version = "0.1", default-features = false }
ethabi = "0.2.2"
linked-hash-map = "0.3"
ethcore-devtools = { path = "../devtools" }
ethcore-rpc = { path = "../rpc" }
ethcore-util = { path = "../util" }
https-fetch = { path = "../util/https-fetch" }
parity-dapps = { git = "https://github.com/wookielnx/parity-ui.git", version = "1.4" }
# List of apps
parity-dapps-status = { git = "https://github.com/wookielnx/parity-ui.git", version = "1.4" }
parity-dapps-home = { git = "https://github.com/wookielnx/parity-ui.git", version = "1.4" }
parity-dapps-wallet = { git = "https://github.com/wookielnx/parity-ui.git", version = "1.4", optional = true }
mime_guess = { version = "1.6.1" }
clippy = { version = "0.0.90", optional = true}

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[features]
default = ["serde_codegen", "extra-dapps"]
extra-dapps = ["parity-dapps-wallet"]
nightly = ["serde_macros"]
dev = ["clippy", "ethcore-rpc/dev", "ethcore-util/dev"]

use-precompiled-js = [
	"parity-dapps-status/use-precompiled-js",
	"parity-dapps-home/use-precompiled-js",
	"parity-dapps-wallet/use-precompiled-js"
]
