[parity]
mode = "dark"
mode_timeout = 15
mode_alarm = 10
chain = "./chain.json"

[account]
unlock = ["0x1", "0x2", "0x3"]
password = ["passwdfile path"]

[signer]
disable = true

[network]
disable = false
warp = false
discovery = true
nat = "any"
min_peers = 10
max_peers = 20

reserved_only = true
reserved_peers = "./path/to/reserved_peers"


[rpc]
disable = true
port = 8180

[ipc]
apis = ["rpc", "eth"]

[dapps]
port = 8080
user = "username"
pass = "password"

[mining]
author = "0xdeadbeefcafe0000000000000000000000000001"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
price_update_period = "hourly"
tx_queue_size = 2048

[footprint]
tracing = "on"
pruning = "fast"
cache_size_db = 128
cache_size_blocks = 16
cache_size_queue = 100
db_compaction = "ssd"
fat_db = true

[snapshots]
disable_periodic = true

[vm]
jit = false

[misc]
logging = "own_tx=trace"
log_file = "/var/log/parity.log"
color = true
